FROM python:3.11

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --upgrade
COPY requirements.txt requirements.txt
RUN pip install requirements.txt

COPY ./mysite .

CMD ["gunicorn", "misite.wsgi:application", "--bind", "0.0.0.0:8000"]